// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	test "github.com/namely/mockery/pkg/fixtures"
	mock "github.com/stretchr/testify/mock"
)

// UsesOtherPkgIface is an autogenerated mock type for the UsesOtherPkgIface type
type UsesOtherPkgIface struct {
	mock.Mock
}

// DoSomethingElse provides a mock function with given fields: obj
func (_m *UsesOtherPkgIface) DoSomethingElse(obj test.Sibling) {
	_m.Called(obj)
}
